theme: jekyll-theme-cayman
title: "Hola"
description: Projecte final 2

[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
